LICENSE

Addressing: https://github.com/kframework/wasm-semantics/issues/1

LICENSE: adding NCSA/UIUC license

---

data.md
tests/simple/conversion.wast
wasm.md

Integer conversion operators

---

.gitignore
META
Makefile
kwasm

Hey @hjorthjort please test this locally (maybe also @cdetrio) and let me know/approve if it works for you and still passes tests.

Simplify Makefile, add instrumentation to kwasm script

---

tests/simple/bitwise.wast
wasm.md

Implementation of `clz`, `ctz`, `popcnt`

---

Makefile
tests/success-haskell.out
tests/success-java.out
tests/success-ocaml.out
wasm.md

Changed the config, related rules and test outputs.

addrs -> funcAddrs and moved it to under moduleInst

---

data.md
media/memory-demo/wasm.k
test.md
tests/proofs/simple-arithmetic-spec.k
tests/simple/control-flow.wast
tests/simple/memory.wast
tests/simple/polymorphic.wast
tests/simple/variables.wast
tests/success-haskell.out
tests/success-java.out
tests/success-ocaml.out
wasm.md

\<stack\> -> \<valstack\>
\</stack\> -> \</valstack\>
.Stack -> .ValStack
STACK -> VALSTACK

stack renamed to valstack

---

data.md
test.md
tests/simple/export.wast
tests/simple/functions_call.wast
tests/simple/identifiers.wast
tests/success-haskell.out
tests/success-java.out
tests/success-ocaml.out
wasm.md

1. Implemented the export sort.
2. Implemented the inline export sort.
3. Fixed the incorrect usage of identifiers of function definition.

Export instr & Inline export instr & function fix

---

kwasm

I forgot how to get the help output, and tried a few standard idioms with no luck. This should mean more input errors (if not all of them) will yield helpful output.

Print help message on more input mistakes

---

test.md
tests/simple/start.wast
wasm.md

Low hanging fruit: Implement the `start` definition.

Start function

---

test.md
tests/simple/arithmetic.wast
tests/simple/bitwise.wast
tests/simple/comments.wast
tests/simple/comparison.wast
tests/simple/constants.wast
tests/simple/control-flow.wast
tests/simple/conversion.wast
tests/simple/data.wast
tests/simple/export.wast
tests/simple/functions_call.wast
tests/simple/identifiers.wast
tests/simple/memory.wast
tests/simple/modules.wast
tests/simple/polymorphic.wast
tests/simple/start.wast
tests/simple/table.wast
tests/simple/variables.wast
wasm.md

now the assertions do not delete elements.
fixed the test file `start.wast`

Cleanup the assertions

---

wasm.md

as all Numeric Instructions return a `Val`, we can make them all functions directly returns `Val` rather than instructions.

change all opcode computation definition to [function]

---

test.md

The ability to test for memory bytes that are set to 0 is useful

Add test for empty memory location

---

data.md
test.md
tests/simple/functions_call.wast
tests/success-java.out
tests/success-ocaml.out
wasm-text.md
wasm.md

Step 1b of the text-format migration

Text format control flow

---

README.md

Found this was necessary to build, should have been in the last PR.

Add `bison` as a dep

---

Jenkinsfile
kwasm

Fix https://github.com/runtimeverification/polkadot-verification/issues/17

More robust kwasm script, use script dir to find preprocessor

---

data.md
kwasm-lemmas.md

data.md: made #chop functional
kwasm-lemmas.md: explicitely marked #chop simplification rules as such

Attribute additions needed for Haskell proofs

---

tests/conformance/look_for_supported.sh
tests/conformance/unparseable.txt
tests/conformance/unsupported-ocaml.txt

Includes a fix to the `look_for_supported.sh` script.

New supported tests

---

Jenkinsfile
data.md

data.md: made pow functions `functional`
deps/k: Updated frontend with haskell backend changes
Part of https://github.com/runtimeverification/polkadot-verification/issues/8

Simple arithmetic spec proven with Haskell backend

---

kwasm-lemmas.md

These lemmas are not necessary anymore.

Remove lemmas

---

wasm.md

Good thing to do anyway, and it seems to help the ewasm-semantics build make progress.

Split growth rule

---

tests/proofs/wrc20-spec.k

Moved memory declaration to its own line.

Fix minor formatting issue in WRC20 spec

---

Makefile

Fixes build on some platforms (tested on osx).

Makefile: add full path to kompile command

---

Makefile

Both me and @sskeirik hade some issues running the concrete memory proof locally. This should make it more reliable.

Change z3 seed

---

Jenkinsfile

This follows the new convention for Jenkinsfiles:
-   Nodes which only have a single line of children all the way down get a single line.
-   Try to line up things where it's sensible.
This makes reading/editing the Jenkinsfile significantly easier (because you can see much more of the file at once).

Jenkinsfile: formatting

---

Makefile
kwasm-lemmas.md

Use WASM-TEXT as main cell for Haskell kompile

---

binary-parser/kwasm_ast.py

The string representation of bytes that Kast needs is hard to achieve in Python.
This is a workaround to that.
It may be more brittle than necessary, so suggestions are welcome.

Bugfix/workaround for creating bytes lists for Kast

---

binary-parser/kwasm_ast.py
binary-parser/wasm2kast.py
wasm-text.md
wasm.md

Store the filename of the module as an optional metadata field

Filename metadata

---

binary-parser/kwasm_ast.py

Wrong type on a store operation

Bugfix binary parser

---

Dockerfile
Jenkinsfile
binary-parser/kwasm_ast.py
binary-parser/test.py
data.md
kwasm
tests/conformance/unparseable.txt
tests/conformance/unsupported-llvm.txt
wasm-text.md
wasm.md
wrc20.md

* Update K dependency to v5.5.139
* functional => total
* Update the lists of `unparseable` and `unsupported-llvm` tests

Update k version

---

.github/workflows/test-pr.yml

Rate limited by dockerhub on unauthorized machines

Add docker login to workflow for pull
