- tests/stack/control-flow.wast
- wasm-syntax.md
- wasm.md
This pull request introduces labels in the semantics, as well as the structured control-flow instructions which use them. It does not implement the inter-function instructions (like `call*`, `invoke`, or `return`).
> Labels control flow

- data.md
- tests/simple/arithmetic.wast
- tests/simple/constants.wast
- tests/simple/control-flow.wast
- tests/simple/functions.wast
- tests/simple/memory.wast
- tests/simple/polymorphic.wast
Switching to using correct comment style in WASM after adding support in K for it.
> .build/k, data, tests/simple/*: using correct wasm format for comments

- tests/simple/control-flow.wast
- wasm.md
I noticed this was missing in the control flow instruction set. [It is used a few times in the official test suite](https://github.com/search?q=unreachable+repo%3AWebAssembly%2Fspec+path%3A%2Ftest%2Fcore&type=Code), whereas the `trap` is not used in any programs as far as I can tell.
From page 69 in official spec:
`unreachable`
1. Trap.
unreachable ˓→ trap
> Add `unreachable` instruction

- README.md
- data.md
- tests/simple/functions.wast
- tests/simple/identifiers.wast
- tests/simple/modules.wast
- wasm.md
This isn't a perfect match of allowable identifiers, but I was having trouble getting the Flex lexer to accept the remaining characters. The unsupported characters are documented, so that a later PR can come through and fix them.
@mrchico I know you were looking at this, can you take a peek and see what you think?
> Update to use proper WASM identifiers

- tests/simple/arithmetic.wast
- tests/simple/bitwise.wast
- tests/simple/comments.wast
- tests/simple/comparison.wast
- tests/simple/constants.wast
- tests/simple/control-flow.wast
- tests/simple/conversion.wast
- tests/simple/functions.wast
- tests/simple/identifiers.wast
- tests/simple/memory.wast
- tests/simple/modules.wast
- tests/simple/polymorphic.wast
- wasm.md
Hey @hjorthjort this prepares for introducing a folded syntax which works with the parser by forcing the use of paranthesis around the concrete syntax. Once it's applied to an argument, the parens go away (so that the semantics are given over the abstract non-paren form).
I also factored out an operator category `ConvOp`. Not sure how I feel about it, but I'll let you decide. It avoids the parsing issues with `_` by building it into the larger tokens (as you did), but still has it type-parametric on the output type (like the other opcodes). I could take it or leave it.
> Simplifying parsing for introduction of folded syntax by requiring paranthesis

- tests/simple/conversion.wast
- wasm.md
Creates separate abstractions for testing and comparison operators. Also groups these abstractions in the same place in the file as `UnOp` and `BinOp`. In that vein, it also moves `ConvOp` to the same place. 
Finally, I took some liberties with cleaning up the conversion operator: I would prefer not to trap on non-existent instructions. Traps seem like they should only happen when the spec says so, not for non-existent instructions.
> Operator abstractions

- LICENSE
- Makefile
- README.md
- data.md
- kwasm
- kwasm-lemmas.md
- test.md
- tests/proofs/simple-arithmetic-spec.k
- wasm.md
@hjorthjort this PR introduces the file `kwasm-lemmas.md`, where you can place facts about WASM simplification which probably shouldn't be directly in the semantics.
Note that we have few semantics which we use for commercial verification (KEVM being one of them), so it's not entirely clear where the "correct" place to put these lemmas is (whether in the definition or not).
Also, we add a couple more proofs to `simple-arithmetic-spec.k`. Feel free to add more if you feel adventurous.
> Separate lemmas into own file for verification, updates to kwasm script

- Makefile
I have the Haskell build working on my end now. Do we want to put it back in by default? Or better to leave it out while it's neither the default concrete or symbolic backend?
> Revert "Makefile: skip haskell backend by default"

- data.md
- kwasm-lemmas.md
- test.md
- tests/proofs/simple-arithmetic-spec.k
- tests/simple/constants.wast
- wasm.md
Guarantees that constants on the stack are in the correct range for their type. It required some updates to the proofs to ensure ranges are respected.
> Constants invariant

- tests/simple/memory.wast
- wasm.md
I found this as I was working on memories. Seems I didn't pay close enough attention when implementing the `(memory X)` instruction. Old implementation treated it as the max size, which is incorrect, it should be the initial size.
I also found some sensible validity checks were missing (not allowing any initial size or max size), so I added those.
> Bugfix: first argument to `memory` is always the initial size

- Dockerfile
- kwasm
- tests/proofs/simple-arithmetic-spec.k
- wasm.md
@hjorthjort if you could test that `./kwasm klab-run tests/simple/arithmetic.wast` and `./kwasm klab-prove tests/proofs/simple-arithmetic-spec.k` work if you put `klab/bin` on your PATH externally, I would appreciate it. If so, let's get this merged.
Remember you need to use `rad-rewrite` branch of KLab.
@mhhf you may be interested as well.
> Add support for KLab in `kwasm` runner script.

- Makefile
- data.md
- test.md
- tests/simple/variables.wast
- tests/success-haskell.out
- tests/success-java.out
- tests/success-ocaml.out
- wasm.md
1. added another sort: syntax Mut ::= ".Mut" | "const" | "var"
2. globals now moved into <mainStore>, and <moduleInst> now has a <globalAddrs> for global addresses.
3. "init_global" is moved to test.md because it is used only for test. Maybe "init_locals" should also be moved to test.md in the future.
4. definition for init_global now changed to "init_global" INDEX GADDR. The test code also changed accordingly.
> Config fix globals

- Jenkinsfile
- Makefile
- README.md
- build
- kwasm
- wasm.md
-   Separate out the step which actually launches KLab from `./kwasm klab-(run|prove)` into new command `./kwasm klab-view`, which allows asynchronously calling them.
-   Use the filename of the spec/program being proved to decide `--state-log-id`, so that many proofs can be run/viewed at once using KLab without overwriting each others results.
-   Add test `test-klab-prove` to make sure that `./kwasm klab-prove` isn't accidentally borked.
-   All testing is handled directly by `Makefile`, instead of relying on `./kwasm test`.
-   Eliminate an unneeded source of branching in the semantics due to bug in rule.
> kwasm: updates pulled over from KEVM

- tests/proofs/simple-arithmetic-spec.k
- tests/simple/control-flow.wast
- wasm.md
Fixes #79 
Previously, we always grabbed the continuation whenever we encountered a
label. However, the correct semantics is that you grab the continuation
when *branching* to a label. When it is encountered without a branch,
it's discarded.
The correct way to write an infinite loop in wasm is
```
loop
(nop) ;; or whatever
(br 0)
end
```
but before this fix, the following was also an infinite loop
```
loop
(nop) ;; or whatever
end
```
> Bugfix: implement correct branching and label semantics

- data.md
- tests/simple/memory.wast
- wasm.md
There was confusion as to whether `WIDTH` was bit or byte width, and `#clearRange` was called incorrectly. This slipped through because the test only checked memory was cleared in the end, but with `WIDTH` being to large it hid the `#clearRange` bug.
> Memory bugfixes

- test.md
- wasm.md
Now we define 4 types of `statements` instead of considering everything as `instruction`:
- Instruction (`Instr`): Administrative or computational instructions. 
- Definition  (`Defn`): The declarations of `type`, `func`, `table`, `mem` etc.
- Auxiliary   (`Auxil`): Functions that only used in our KWASM semantics but not in the official specification including assertions, invoke a function by imported name, and maybe instantiate a module?
- The Declaration of a module.
> Categorizing declarations for a better program structure

- test.md
- wasm.md
The fact that `trap` eats up execution is really part of the Wasm semantics. I want to be as principled as possible about the `WASM` module to contain the full Wasm semantics, and to keep embedder stuff located outside. 
Now that we have this nice sort hierarchy, we can finally put `trap` semantics in `WASM`. Do you agree?
> Put trap semantics into WASM module now that we can do it properly

- data.md
- test.md
- tests/simple/table.wast
- wasm.md
`elem` is used to add new elements to an empty table (just like the official test cases).
`call_indirect` is used to call a function in a table, with the index at the top of the stack.
The newly added test case is copied from /tests/wasm-tests/test/core/elem.wast.
> Table initialization and call_indirect

- test.md
- tests/simple/arithmetic.wast
- tests/simple/bitwise.wast
- tests/simple/comments.wast
- tests/simple/comparison.wast
- tests/simple/constants.wast
- tests/simple/control-flow.wast
- tests/simple/conversion.wast
- tests/simple/data.wast
- tests/simple/export.wast
- tests/simple/functions_call.wast
- tests/simple/identifiers.wast
- tests/simple/memory.wast
- tests/simple/modules.wast
- tests/simple/polymorphic.wast
- tests/simple/start.wast
- tests/simple/table.wast
- tests/simple/variables.wast
- tests/success-haskell.out
- tests/success-java.out
- tests/success-ocaml.out
- wasm.md
We will need this for imports.
I started working on adding more `Auxil` instructions from the official interpreter and started with `register`. This way of storing allocated modules is roughly what we discussed, IIRC.
One thing I want to discuss is whether we want to have a separate "embedder" module, which would imitate the reference interpreter, and have `test.md` be our own tests, that could optionally be discarded after we pass the official tests. Now I'm keeping them in the same file, which seems wrong. But that refactoring can be done at a later point.
I'd argue this fixes #99, because that issue is mostly about registering modules. We haven't started on imports yet, but I conjecture they would be pretty straightforward with this configuration.
> Registering modules

- data.md
- test.md
- tests/simple/export.wast
- tests/simple/functions_call.wast
- tests/simple/modules.wast
- tests/simple/trap.wast
- wasm.md
Implemented assert_trap and assert_return.
Added some pretty nice test cases.
We need to notice that assert_return takes an `Action`, and the parameters must be specified inline rather than using separate const instructions before it. (just as conformance test cases)
> Conformance assert_return and assert_trap

- test.md
- tests/simple/data.wast
- tests/simple/export.wast
- tests/simple/functions_call.wast
- tests/simple/identifiers.wast
- tests/simple/memory.wast
- tests/simple/start.wast
- tests/simple/variables.wast
- tests/success-haskell.out
- tests/success-java.out
- tests/success-ocaml.out
- wasm.md
The spec explicitly allows inline modules, like we had earlier, where definitions could be placed at the top level, i.e., no need to explicitly use `module` keyword. See the official test `inline_module.wast` for an example.
The rule that allows this is the very last one in `wasm.md`, which kicks in only when a `Defn` is encountered and there is no current module. In that case, a module is instantiated.
I'm not a huge fan of the fact that we can (and do) use a simple `(module)` statement to create a module and then have it hanging around as the current module. I'd prefer if we actually were a bit stricter so that the `curModIdx` cell is cleared after a module declaration is done. This messes a lot with our assertions, though, and I haven't really got that working yet.
The new rule relies …
> (Re)implement proper inline modules, and implement global declarations

- tests/simple/modules.wast
- wasm.md
This traverses the definitions in a module and orders them appropriately for allocation and instantiation. Imports are yet to be implemented, but I added them to the ordering for completeness.
> Structuring and ordering definitions in modules

- data.md
- tests/proofs/simple-arithmetic-spec.k
- tests/simple/control-flow.wast
- wasm.md
This solves most of the problems in issue https://github.com/kframework/wasm-semantics/issues/77.
Now instruction are categorized into `plaininstr`, `blockinstr`, and some still named as `instr`, according to the specs.
`plaininstr` could be written in folded form, so we can use one rule to represent all folded forms rather than needing rules for each of them. Also, we do not have to wrap instructions in parenthesis.
These instructions are still named as `instr`:
- administrative instructions, including `invoke idx`, `trap`, `label`, `init_xxx`.
- `blockinstr` when in the format of being wrapped in parenthesis.
- helper instructions we defined to help computation.
> Instruction refactoring

- Makefile
Kompiling to haskell no longer produces a `kore.txt` file, but rather a `compiled.txt` file. Due to the nature of Makefiles, this issue meant that make constantly found the `kore.txt` file lacking, and thus always rebuilt the haskell backend regardless of if it's necessary or not. That's a lot of wasted time every time `make build` is called.
> "Correct" filename for kompiling to Haskell

- Makefile
- tests/proofs/loops-spec.k
- tests/proofs/simple-arithmetic-spec.k
We only need to test that `klab-prove` works at all, not to run it on all the proofs.
> Shorter klab prove target, CI will finish quicker

- test.md
This is a very small PR.
assert_return now asserts both the correct type and the correct value.
For example, if the return type of a function is `<i32>`, assert_return must give an `<i32>` return value rather than any of `<i32>` and `<i64>`.
This fix will benefit the type conversion tests.
> assert_return should assert the exact return value

- data.md
Add a conversion from String to WasmString, useful for making concrete WasmStrings inside a semantics. I use this in Ewasm, which has a few special strings, such as `"ethereum"` and `"main"`.
> Unparse WasmString

- Makefile
- data.md
- kwasm-lemmas.md
- test.md
- tests/proofs/loops-spec.k
- tests/proofs/simple-arithmetic-spec.k
- wasm-text.md
- wasm.md
Introduce a separate module for the text format.
Instead of having all these rules in the core syntax, we can keep them in a separate module. This both makes the core semantics smaller, more like the official spec, and a smaller compile target for the binary format.
This is not a full separation of text format and core semantics. The following remains:
1a. Getting rid of any mentions identifiers in the definitions in the core semantics, ideally by making all the definitions more abstract in the core semantics, and only giving their text format, with identifiers and all, in the text semantics. This can be achieved since this PR splits the definitions of `Index`, and all lookups pass through the `#ContextLookup` function.
1b. Getting rid of identifiers on branches and labels in the core …
> Text format

- README.md
Add instructions for getting the deps for LLVM backend, since it's standard now.
> Add LLVM deps to Readme

- .gitignore
- Jenkinsfile
- Makefile
- README.md
- kwasm
-   Better dependencies on generated directories.
-   Quieter tangling and kompiling.
-   Switch to LLVM backend default in runner script/Makefile.
-   Allow passing options to `kompile` when using Makefile.
-   Guard against performance regressions in the tests.
> Build updates for quieter more reliable build

- kwasm
-   K_OPTS has a default, but can be overridden in `./kwasm`
-   Update K submodule to include new pyk changes.
> Pyk updates, kwasm allows overriding K_OPTS

- Jenkinsfile
- Makefile
Now that the dependencies are updated, this proof should pass.
> Makefile: memory-spec.k.prove: Use the Haskell backend

- Makefile
- kwasm-lemmas.md
- tests/proofs/locals-spec.k
- tests/proofs/loops-spec.k
- tests/proofs/memory-concrete-type-spec.k
- tests/proofs/memory-symbolic-type-spec.k
- tests/proofs/simple-arithmetic-spec.k
* `kwasm-lemmas.md`: marked some simplification rules as such
* `tests/proofs/*-spec.k`: workaround a claims-detection frontend bug
* `Makefile`: updated to run all proofs with the Haskell backend
> Several updates to allow running proofs in Haskell.

- Makefile
This lets me use a different K build without forcibly overriding the submodule by setting `K_RELEASE` in my shell environment. The `kwasm` script already reads this variable.
> Makefile: Take K_RELEASE from environment, if set

- tests/proofs/wrc20-spec.k
This PR should fix a bug found when running the spec with the Haskell backend. 
Note that the spec was run on the following branch of `wasm-semantics` https://github.com/kframework/wasm-semantics/tree/kore-1395, with this modification.
> Modify funcs cell in wrc20

- data.md
- wasm.md
It's not immediately obvious to me that we can remove the `#take` and `#drop` altogether, so this just makes them use integer values instead.
> data, wasm: switch to using integer for take/drop lengths

- Jenkinsfile
Seems the conformance step is getting timed out. Not sure if that's a regression on our end, of the server capacity or of K. But seeing how it is blocking other PRs, I say we bump the available time.
EDIT: Some other PRs saw a timeout in the proving step, even after the time was increased in #299. I added some margin there as well.
> Bump time for conformance step in CI

- Makefile
- data.md
- kwasm-lemmas.md
- tests/proofs/memory-symbolic-type-spec.k
For the balance proof in Ewasm, splitting up `#getRange` and `#setRange` takes *a lot* of time. So I think it's worth keeping the expansion concrete (like we intended originally).
Also, making `#wrap` functional helps with reasoning, but `modInt` isn't functional. I suggest we change it to use `&Int` instead. I think that is a) more in line with the semantics of `#wrap`, and b) will allow us to have lemmas that rewrite `modInt` to `#wrap` when possible, without risking infinite rewrites. I would want us to rely more on `#wrap`, `&Int`, `|Int`, `<<Int` and `>>Int` in the future, because they are total and make for simpler lemmas when reasoning about bits than `modInt`, `+Int`, `/Int` and `*Int`. I'm running that locally now, to make sure it checks out, and to time it.
> Concrete #setRange

- wasm.md
This separates the definitions of the functions, memories and tables (which can come in several different formats) from their actual allocations (which have specific requirements)
A few birds in one stone here:
1. Fixes https://github.com/kframework/ewasm-semantics/issues/15
2. Fixes #308 
3. Separates text-format definitions from their core-format behavior (of allocating `funcs`/`mems`/`globs`/`tables`. Now the definitions are purely a text format thing, and the allocations they trigger can't be directly expressed in a module.
It's still not quite the way it works in the official spec, where `alloc[func/def/mem/table]` is a function that acts on the entire store, but its closer.
I also removed cases where allocations cause `trap`. Those shouldn't really be trapping, it's a validity …
> Allocator Statements

- data.md
- wasm.md
This makes `_++_`, `#take`, and `#drop` total (and adds the `functional` attribute for them).
This should make many definedness conditions in proofs simplify out a lot sooner.
The one catch is that now `#take` and `#drop` have weird behavior on the empty `.ValStack`, that is they always return the empty `.ValStack` instead of beind undefined. Because of the type-safety proof on the semantics, this should be OK. I checked all the call sites of `#take` and `#drop` and they should be covered by the type-safety proof.
> Make some functions total

- kwasm-lemmas.md
This allows us to include the lemmas file into the rule merger for Polkadot, because otherwise the LLVM backend complains about function symbols on the LHS of rules.
> kwasm-lemmas: only include this module when targeting symbolic backends

- data.md
- numeric.md
- wasm.md
This takes several functions which cause `#Ceil` conditions to happen in rule-merging and either (i) marks them as total if they aren't, or (ii) makes them total if they aren't and then marks them so.
One thing that is a bugfix is that `#set` was not total before. If the key was present in the Map, but _was not_ an `Int`, then `#set` was undefined. By having the other case be `[owise]`, we make it actually total here.
> More total functions

- Makefile
PR #320 introduced an error, the "Simple" tests no longer get run at all, so the stage trivially passes.
I identified the issue in the Makefile.
> Fix Makefile error

- Makefile
This lingering `float` test broke `make test`, which is a convenient way to run all tests.
> Remove float test command without target

- data.md
- kwasm-lemmas.md
-   Several lemmas over `#get` removed.
-   Re-organize and minor documentation of `kwasm-lemmas.md`.
-   Standardization of comparison directions (eg. `0 <Int WIDTH` instead of `WIDTH >Int 0`)
This may be easier to review commit-by-commit with `git log -p`, and in some cases `git show COMMIT_ID -b`
> Cleanups and organization

- Dockerfile
- Jenkinsfile
- Makefile
- kwasm
This uses the published Dockerhub images for K on CI instead of building it in the Jenkinsfile, which will make the overall CI time less.
Both the `Makefile` and the `kwasm` script are modified to have the following behavior about where to pull `K_RELEASE` from (and thus `krun`, `kprove`, `kore-exec`, etc...):
-   If the user sets `K_RELEASE`, use that version.
-   If the submodule is built, use the submodule version.
-   Otherwise, use `which kompile` to find a global or user install of K, and use that build.
> Use Dockerhub images for CI

- data.md
- test.md
- tests/bad-proofs/mod-on-negative-spec.k.expected
- tests/simple/data.wast
- tests/simple/functions_call.wast
- tests/simple/text2abstract.wast
- tests/success-llvm.out
- wasm-text.md
- wasm.md
In preparation for the extraction of identifiers and removing `#ContextLookup` for definitions of tables, functions, globals, and memories.
This passes each module through an `unfoldDefns` function. Previously we were doing some of this unfolding at parse time, with macros, and some at runtime. Now we do it all ahead of time.
Some tests are updated to reflect that we no longer support unfolding at runtime, so only definitions that are declared properly in modules can be desugared. We could in principle support all the syntactic sugars, but I think it would make the desugaring code a lot messier and verbose (and departing from the official spec), since we would have to deal with definitions interleaved with statements while keeping track of which module we are in.
This one might be easiest …
> Unfold definitions

- kwasm-lemmas.md
Many of the lemmas we're using are now included in `INT-SYMBOLIC` directly.
This uses those instead of repeating them here.
> Use upstreamed integer symbolic reasoning

- Jenkinsfile
- Makefile
In refactoring the KEVM and KMichelson makefiles, I came up with several improvements over the original structure.
This implements those improvements on this Makefile as well.
-   Per-build `*_main_file`, `*_main_module`, and `*_syntax_module`
-   Separate `LLVM_KOMPILE_OPTS` and `HASKELL_KOMPILE_OPTS`
-   Using `RELEASE` to control both `K_BUILD_TYPE` and optimization level when kompiling.
-   Remove use of `git submodule update --init --recursive` from Makefile (makes it easier to experiment with custom submodules without having to commit them.
> Standardize Makefile

- test.md
- wasm-text.md
- wasm.md
This PR moves us closer to the official spec by:
1. Structuring modules fully into separate lists for each kind of definition.
2. Performing the module structuring as part of the transformation from text format to abstract format.
> Sort text module

- test.md
- tests/proofs/wrc20-spec.k
- tests/simple/functions_call.wast
- tests/simple/identifiers.wast
- tests/simple/start.wast
- tests/simple/table.wast
- tests/simple/text2abstract.wast
- wasm-text.md
- wasm.md
The tests are updated, because we now don't support function IDs outside of modules, and the ID isn't stored, so the assertions can't check for them.
> Remove contextlookup for functions

- data.md
- numeric.md
- tests/proofs/wrc20-spec.k
- wasm-text.md
- wasm.md
These are no longer needed, now that we resolve local identifiers in preprocessing.
> Remove named valtypes

- tests/proofs/wrc20-spec.k
- tests/simple/functions_call.wast
- wasm-text.md
- wasm.md
This is in preparation of getting rid of `#ContextLookup` for types.
> Type desugaring during text -> core phase

- test.md
- tests/simple/table.wast
- wasm-text.md
- wasm.md
* Allow `elem` declarations to have the keyword `func` in them
* Specify in `allocfunc` where the function should be stored
* Unfold instructions inlined into `offset`s.
* Unfold global initializers.
* Break out `#clearConfig` from the testing module, so that it can be used without importing all of the testing module.
> Elrond-related fixes to unfolding

- Makefile
- README.md
- data.md
- kwasm
This PR does 4 things:
-   Adds the `--bug-report` option directly to `kwasm` runner for ease of access.
-   Uses the now frontend-exposed `--debugger --debug-script` for the `--repl` option.
-   Makes the increased stack/memory limits for `krun/kprove` globally set.
-   Updates the argument/option parsing to be the same as KEVM.
> KWasm updates pulled over from KEVM

- auxil.md
- data.md
- numeric.md
- test.md
- wasm-text.md
- wasm.md
This is in preparation for switching to a Bison-generated parser. The top-level syntax module still imports all the semantics modules, so use of `^Int` and similar are still parseable, but that will be removed.
> Syntax modules

- binary-parser/kwasm_ast.py
- binary-parser/wasm2kast.py
- tests/proofs/loops-spec.k
- wasm-text.md
- wasm.md
We introduce
```
syntax BlockMetaData ::= #funcBlockInfo ( Int ) [klabel(funcBlockInfo), symbol]
| #blockInfo     ( Int ) [klabel(blockInfo), symbol]
```
In wasm_kast.py, we can only assign a unique #blockInfo(block_id) to #block, #if and #loop, not the function.
the `#funcBlockInfo` is used in the following rule
```
rule <instrs> ( invoke FADDR )
=> init_locals #revs(#take(lengthValTypes(TDOMAIN), VALSTACK)) ++ #zero(TLOCALS)
~> #block([TRANGE], INSTRS, #funcBlockInfo(FADDR))
~> frame MODIDX TRANGE #drop(lengthValTypes(TDOMAIN), VALSTACK) LOCAL
...
</instrs>
```
> introduce BlockMetaData for measureing wasm coverage

- Makefile
Addresses https://github.com/kframework/kore/issues/2624
> Using '+=' instead of '=' when setting KPROVE_OPTS

- Dockerfile
- README.md
This PR reflects a pending change in the upstream K distribution; it updates package files and documentation to reflect the new version of Z3 we require.
> Bump Z3 version to 4.8.15

- Makefile
- binary-parser/kwasm_ast.py
- binary-parser/test_kwasm_ast.py
This PR fixes the `KBytes` function in `binary-parser`, which converts Python `bytes` to K `Bytes`. The current implementation puts extra backslashes.  
```python
>>> from kwasm_ast import KBytes
>>> KBytes(bytes([0, 65, 255])).token
'b"\\x00A\\xff"'
>>> KBytes(bytes([0, 65, 255])).token == 'b"\x00\x41\xff"'
False
>>> KBytes(bytes([0x0, 0x41, 0xff])).token == 'b"\x00\x41\xff"'
False
```
After the fix:
```python
>>> from kwasm_ast import KBytes
>>> KBytes(bytes([0, 65, 255])).token == 'b"\x00A\xff"'
True
>>> KBytes(bytes([0, 65, 255])).token == 'b"\x00\x41\xff"'
True
>>> KBytes(bytes([0x0, 0x41, 0xff])).token == 'b"\x00\x41\xff"'
True
```
This solution is taken from [`avm-semantics`](https://github.com/runtimeverification/avm-semantics/blob/35a75917cad492bd37485db82345d218f9c4bd74/kavm/src/ …
> Fix `KBytes`

- .github/workflows/master-push.yml
- Jenkinsfile
This switches from using Jenkinsfile + Jenkins-based dependency updater to using a GH job on master push with the devops action for triggering updates.
> Switch to GH Runner based dependency updater
